//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Cst.SmartX.Piloto.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RM.Cst.SmartX.Piloto.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano da Fabricação.
        /// </summary>
        internal static string AnoDaFabricacao {
            get {
                return ResourceManager.GetString("AnoDaFabricacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano do Modelo.
        /// </summary>
        internal static string AnoDoModelo {
            get {
                return ResourceManager.GetString("AnoDoModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano modelo pode ser no máximo 1 ano maior que o ano de fabricação.
        /// </summary>
        internal static string AnoModeloNaoPodeSerMaiorQueAnoFabricacao {
            get {
                return ResourceManager.GetString("AnoModeloNaoPodeSerMaiorQueAnoFabricacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de veiculo.
        /// </summary>
        internal static string CadastroVeiculos {
            get {
                return ResourceManager.GetString("CadastroVeiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Coligada do Relatório.
        /// </summary>
        internal static string CodigoColigadaReport {
            get {
                return ResourceManager.GetString("CodigoColigadaReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Coligada.
        /// </summary>
        internal static string CodigoDaColigada {
            get {
                return ResourceManager.GetString("CodigoDaColigada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Cor.
        /// </summary>
        internal static string CodigoDaCor {
            get {
                return ResourceManager.GetString("CodigoDaCor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Marca.
        /// </summary>
        internal static string CodigoDaMarca {
            get {
                return ResourceManager.GetString("CodigoDaMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Veículo.
        /// </summary>
        internal static string CodigoDoVeiculo {
            get {
                return ResourceManager.GetString("CodigoDoVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Opcional.
        /// </summary>
        internal static string CodigoOpcional {
            get {
                return ResourceManager.GetString("CodigoOpcional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Opcional do Veiculo.
        /// </summary>
        internal static string CodigoOpcionalVeiculo {
            get {
                return ResourceManager.GetString("CodigoOpcionalVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Relatório.
        /// </summary>
        internal static string CodigoReport {
            get {
                return ResourceManager.GetString("CodigoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Veiculo.
        /// </summary>
        internal static string CodigoVeiculo {
            get {
                return ResourceManager.GetString("CodigoVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustível.
        /// </summary>
        internal static string Combustivel {
            get {
                return ResourceManager.GetString("Combustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo de Cor.
        /// </summary>
        internal static string CorModel {
            get {
                return ResourceManager.GetString("CorModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cor.
        /// </summary>
        internal static string CorObject {
            get {
                return ResourceManager.GetString("CorObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcool.
        /// </summary>
        internal static string CstAlcool {
            get {
                return ResourceManager.GetString("CstAlcool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Veiculos.
        /// </summary>
        internal static string CstCadastroVeiculos {
            get {
                return ResourceManager.GetString("CstCadastroVeiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        internal static string CstDiesel {
            get {
                return ResourceManager.GetString("CstDiesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flex.
        /// </summary>
        internal static string CstFlex {
            get {
                return ResourceManager.GetString("CstFlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasolina.
        /// </summary>
        internal static string CstGasolina {
            get {
                return ResourceManager.GetString("CstGasolina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Da Cor.
        /// </summary>
        internal static string DescricaoDaCor {
            get {
                return ResourceManager.GetString("DescricaoDaCor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Da Marca.
        /// </summary>
        internal static string DescricaoDaMarca {
            get {
                return ResourceManager.GetString("DescricaoDaMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Marca .
        /// </summary>
        internal static string MarcaModel {
            get {
                return ResourceManager.GetString("MarcaModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string MarcaObject {
            get {
                return ResourceManager.GetString("MarcaObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo de Moeda.
        /// </summary>
        internal static string MoedaModel {
            get {
                return ResourceManager.GetString("MoedaModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda.
        /// </summary>
        internal static string MoedaObject {
            get {
                return ResourceManager.GetString("MoedaObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcionais do Veiculo.
        /// </summary>
        internal static string OpcionaisVeiculo {
            get {
                return ResourceManager.GetString("OpcionaisVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Opcional.
        /// </summary>
        internal static string OpcionalModel {
            get {
                return ResourceManager.GetString("OpcionalModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcional.
        /// </summary>
        internal static string OpcionalObject {
            get {
                return ResourceManager.GetString("OpcionalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Opcional Veiculo.
        /// </summary>
        internal static string OpcionalVeiculoModel {
            get {
                return ResourceManager.GetString("OpcionalVeiculoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo Opcional.
        /// </summary>
        internal static string OpcionalVeiculoObject {
            get {
                return ResourceManager.GetString("OpcionalVeiculoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Parâmetros.
        /// </summary>
        internal static string ParametrosModel {
            get {
                return ResourceManager.GetString("ParametrosModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros.
        /// </summary>
        internal static string ParametrosObject {
            get {
                return ResourceManager.GetString("ParametrosObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Símbolo.
        /// </summary>
        internal static string Simbolo {
            get {
                return ResourceManager.GetString("Simbolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Veiculo.
        /// </summary>
        internal static string VeiculoModel {
            get {
                return ResourceManager.GetString("VeiculoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo.
        /// </summary>
        internal static string VeiculoObject {
            get {
                return ResourceManager.GetString("VeiculoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendido.
        /// </summary>
        internal static string Vendido {
            get {
                return ResourceManager.GetString("Vendido", resourceCulture);
            }
        }
    }
}
